const mongoose = require('mongoose');

const studentSchema = new mongoose.Schema({
  name: String,
  classStudying: String,
  dob: Date,
  email: String,
  phoneNumber: String,
  studentID: String,
  password: String,  // Autogenerated
  quizzes: [{
    quizID: String,
    quizName: String,
    studentScore: {type:Number, default:0},
    attempted:{type:Boolean, default:false},
    // reportCard: String
  }]
}, {
  timestamps: true
});

const Student = mongoose.model('Student', studentSchema);
module.exports = Student;
